import type { ComponentProps } from 'react';
import type { Href } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';

export type ToolCategoryId =
  | 'estimation'
  | 'projects'
  | 'engineering'
  | 'safety'
  | 'documents'
  | 'analytics';

/** Local calculators / UIs that ship today. Others open the placeholder screen until backend phases land. */
export type ToolImplementation = 'live' | 'placeholder';

export interface ToolEntry {
  id: string;
  title: string;
  description: string;
  category: ToolCategoryId;
  phase: 'basic' | 'mid' | 'advanced';
  implementation: ToolImplementation;
  href: Href;
  icon: ComponentProps<typeof Ionicons>['name'];
}

export const ALL_TOOLS: ToolEntry[] = [
  // Category 1 — Estimation
  {
    id: 'cost-estimator',
    title: 'Cost Estimator',
    description: 'Area, grade, labour, contingency & tax',
    category: 'estimation',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/cost-estimator',
    icon: 'calculator-outline',
  },
  {
    id: 'material-quantity',
    title: 'Material Quantity',
    description: 'Bricks, tiles, paint & sand quantities',
    category: 'estimation',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/material-quantity',
    icon: 'layers-outline',
  },
  {
    id: 'roi',
    title: 'ROI Calculator',
    description: 'Return on construction investment',
    category: 'estimation',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/roi',
    icon: 'trending-up-outline',
  },
  {
    id: 'budget-tracker',
    title: 'Budget Tracker',
    description: 'Planned vs actual by category (per project)',
    category: 'estimation',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/budget-tracker',
    icon: 'wallet-outline',
  },
  {
    id: 'bid-comparison',
    title: 'Bid Comparison',
    description: 'Weighted score across up to 6 vendors',
    category: 'estimation',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/bid-comparison',
    icon: 'bar-chart-outline',
  },
  // Category 2 — Projects
  {
    id: 'gantt',
    title: 'Gantt / Timeline',
    description: 'Project schedule & dependencies',
    category: 'projects',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/gantt',
    icon: 'calendar-outline',
  },
  {
    id: 'task-manager',
    title: 'Task Manager',
    description: 'Task list with due dates per project',
    category: 'projects',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/task-manager',
    icon: 'checkbox-outline',
  },
  {
    id: 'daily-site-log',
    title: 'Daily Site Log',
    description: 'Weather, workforce, photos, sign-off',
    category: 'projects',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/daily-site-log',
    icon: 'clipboard-outline',
  },
  {
    id: 'milestone-tracker',
    title: 'Milestone Tracker',
    description: 'Planned vs forecast dates',
    category: 'projects',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/milestone-tracker',
    icon: 'flag-outline',
  },
  {
    id: 'resource-scheduler',
    title: 'Resource Scheduler',
    description: 'People, plant & materials allocation',
    category: 'projects',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/resource-scheduler',
    icon: 'people-outline',
  },
  {
    id: 'cpm',
    title: 'CPM Calculator',
    description: 'Critical path on activities',
    category: 'projects',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/cpm',
    icon: 'git-branch-outline',
  },
  // Category 3 — Engineering
  {
    id: 'concrete-mix',
    title: 'Concrete Mix',
    description: 'Cement, sand, aggregate & water',
    category: 'engineering',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/concrete-mix',
    icon: 'cube-outline',
  },
  {
    id: 'load-bearing',
    title: 'Load Bearing',
    description: 'Axial capacity & factor of safety',
    category: 'engineering',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/load-bearing',
    icon: 'analytics-outline',
  },
  {
    id: 'rebar',
    title: 'Rebar Calculator',
    description: 'Bar count, weight & steel cost',
    category: 'engineering',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/rebar',
    icon: 'git-network-outline',
  },
  {
    id: 'foundation',
    title: 'Foundation',
    description: 'Footing size from load & SBC',
    category: 'engineering',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/foundation',
    icon: 'square-outline',
  },
  {
    id: 'beam-deflection',
    title: 'Beam Deflection',
    description: 'Deflection vs span limits',
    category: 'engineering',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/beam-deflection',
    icon: 'remove-outline',
  },
  {
    id: 'seismic',
    title: 'Seismic Load',
    description: 'Base shear & floor forces (code-based)',
    category: 'engineering',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/seismic',
    icon: 'earth-outline',
  },
  // Category 4 — Safety
  {
    id: 'safety-checklist',
    title: 'Site Safety Checklist',
    description: 'Inspection templates & scoring',
    category: 'safety',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/safety-checklist',
    icon: 'list-outline',
  },
  {
    id: 'incident-report',
    title: 'Incident Report',
    description: 'Injuries, near-miss & evidence',
    category: 'safety',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/incident-report',
    icon: 'medkit-outline',
  },
  {
    id: 'ppe-tracker',
    title: 'PPE Tracker',
    description: 'Issue, expiry & stock',
    category: 'safety',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/ppe-tracker',
    icon: 'shirt-outline',
  },
  {
    id: 'permit-manager',
    title: 'Permit Manager',
    description: 'Permits, expiry & reminders',
    category: 'safety',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/permit-manager',
    icon: 'document-text-outline',
  },
  {
    id: 'osha-compliance',
    title: 'OSHA / Compliance',
    description: 'Clause checklists & audit score',
    category: 'safety',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/osha-compliance',
    icon: 'shield-checkmark-outline',
  },
  // Category 5 — Documents
  {
    id: 'invoice-generator',
    title: 'Invoice Generator',
    description: 'Line items, tax & PDF',
    category: 'documents',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/invoice-generator',
    icon: 'receipt-outline',
  },
  {
    id: 'contract-builder',
    title: 'Contract Builder',
    description: 'Templates & clauses to PDF',
    category: 'documents',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/contract-builder',
    icon: 'document-attach-outline',
  },
  {
    id: 'progress-report',
    title: 'Progress Report',
    description: 'Period report with photos',
    category: 'documents',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/progress-report',
    icon: 'newspaper-outline',
  },
  {
    id: 'rfi-tracker',
    title: 'RFI Tracker',
    description: 'Requests for information & responses',
    category: 'documents',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/rfi-tracker',
    icon: 'chatbubbles-outline',
  },
  {
    id: 'punch-list',
    title: 'Punch List',
    description: 'Snags, photos & verification',
    category: 'documents',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/punch-list',
    icon: 'list-circle-outline',
  },
  // Category 6 — Analytics
  {
    id: 'analytics-dashboard',
    title: 'Analytics Dashboard',
    description: 'Portfolio KPIs & SPI/CPI',
    category: 'analytics',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/analytics-dashboard',
    icon: 'pie-chart-outline',
  },
  {
    id: 'bim-viewer',
    title: 'BIM Viewer',
    description: 'Viewer links & ACC / cloud sessions',
    category: 'analytics',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/bim-viewer',
    icon: 'apps-outline',
  },
  {
    id: 'drone-report',
    title: 'Drone / Site Photos',
    description: 'Geo-tagged photo reports',
    category: 'analytics',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/drone-report',
    icon: 'airplane-outline',
  },
  {
    id: 'carbon-footprint',
    title: 'Carbon Footprint',
    description: 'Embodied CO₂ from key inputs',
    category: 'analytics',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/carbon-footprint',
    icon: 'leaf-outline',
  },
  {
    id: 'ai-risk-predictor',
    title: 'AI Risk Predictor',
    description: 'Advisory risk scores (on-device)',
    category: 'analytics',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/ai-risk-predictor',
    icon: 'sparkles-outline',
  },
];

export const CATEGORY_LABELS: Record<ToolCategoryId | 'all', string> = {
  all: 'All',
  estimation: 'Estimation',
  projects: 'Projects',
  engineering: 'Engineering',
  safety: 'Safety',
  documents: 'Documents',
  analytics: 'Analytics',
};
