import type { ComponentProps } from 'react';
import type { Href } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';

export type ToolCategoryId =
  | 'estimation'
  | 'projects'
  | 'engineering'
  | 'safety'
  | 'documents'
  | 'analytics'
  | 'reference'
  | 'instruments'
  | 'mep'
  | 'knowledge'
  | 'procurement';

/** Local calculators / UIs that ship today. Others open the placeholder screen until backend phases land. */
export type ToolImplementation = 'live' | 'placeholder';

export interface ToolEntry {
  id: string;
  title: string;
  description: string;
  category: ToolCategoryId;
  phase: 'basic' | 'mid' | 'advanced';
  implementation: ToolImplementation;
  href: Href;
  icon: ComponentProps<typeof Ionicons>['name'];
}

export const ALL_TOOLS: ToolEntry[] = [
  // Category 1 — Estimation
  {
    id: 'cost-estimator',
    title: 'Cost Estimator',
    description: 'Area, grade, labour, contingency & tax',
    category: 'estimation',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/cost-estimator',
    icon: 'calculator-outline',
  },
  {
    id: 'material-quantity',
    title: 'Material Quantity',
    description: 'Bricks, tiles, paint & sand quantities',
    category: 'estimation',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/material-quantity',
    icon: 'layers-outline',
  },
  {
    id: 'roi',
    title: 'ROI Calculator',
    description: 'Return on construction investment',
    category: 'estimation',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/roi',
    icon: 'trending-up-outline',
  },
  {
    id: 'budget-tracker',
    title: 'Budget Tracker',
    description: 'Planned vs actual by category (per project)',
    category: 'estimation',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/budget-tracker',
    icon: 'wallet-outline',
  },
  {
    id: 'bid-comparison',
    title: 'Bid Comparison',
    description: 'Weighted score across up to 6 vendors',
    category: 'estimation',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/bid-comparison',
    icon: 'bar-chart-outline',
  },
  // Category 2 — Projects
  {
    id: 'gantt',
    title: 'Gantt / Timeline',
    description: 'Project schedule & dependencies',
    category: 'projects',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/gantt',
    icon: 'calendar-outline',
  },
  {
    id: 'task-manager',
    title: 'Task Manager',
    description: 'Task list with due dates per project',
    category: 'projects',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/task-manager',
    icon: 'checkbox-outline',
  },
  {
    id: 'daily-site-log',
    title: 'Daily Site Log',
    description: 'Weather, workforce, photos, sign-off',
    category: 'projects',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/daily-site-log',
    icon: 'clipboard-outline',
  },
  {
    id: 'milestone-tracker',
    title: 'Milestone Tracker',
    description: 'Planned vs forecast dates',
    category: 'projects',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/milestone-tracker',
    icon: 'flag-outline',
  },
  {
    id: 'resource-scheduler',
    title: 'Resource Scheduler',
    description: 'People, plant & materials allocation',
    category: 'projects',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/resource-scheduler',
    icon: 'people-outline',
  },
  {
    id: 'cpm',
    title: 'CPM Calculator',
    description: 'Critical path on activities',
    category: 'projects',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/cpm',
    icon: 'git-branch-outline',
  },
  // Category 3 — Engineering
  {
    id: 'concrete-mix',
    title: 'Concrete Mix',
    description: 'Cement, sand, aggregate & water',
    category: 'engineering',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/concrete-mix',
    icon: 'cube-outline',
  },
  {
    id: 'load-bearing',
    title: 'Load Bearing',
    description: 'Axial capacity & factor of safety',
    category: 'engineering',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/load-bearing',
    icon: 'analytics-outline',
  },
  {
    id: 'rebar',
    title: 'Rebar Calculator',
    description: 'Bar count, weight & steel cost',
    category: 'engineering',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/rebar',
    icon: 'git-network-outline',
  },
  {
    id: 'foundation',
    title: 'Foundation',
    description: 'Footing size from load & SBC',
    category: 'engineering',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/foundation',
    icon: 'square-outline',
  },
  {
    id: 'beam-deflection',
    title: 'Beam Deflection',
    description: 'Deflection vs span limits',
    category: 'engineering',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/beam-deflection',
    icon: 'remove-outline',
  },
  {
    id: 'seismic',
    title: 'Seismic Load',
    description: 'Base shear & floor forces (code-based)',
    category: 'engineering',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/seismic',
    icon: 'earth-outline',
  },
  // Category 4 — Safety
  {
    id: 'safety-checklist',
    title: 'Site Safety Checklist',
    description: 'Inspection templates & scoring',
    category: 'safety',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/safety-checklist',
    icon: 'list-outline',
  },
  {
    id: 'incident-report',
    title: 'Incident Report',
    description: 'Injuries, near-miss & evidence',
    category: 'safety',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/incident-report',
    icon: 'medkit-outline',
  },
  {
    id: 'ppe-tracker',
    title: 'PPE Tracker',
    description: 'Issue, expiry & stock',
    category: 'safety',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/ppe-tracker',
    icon: 'shirt-outline',
  },
  {
    id: 'permit-manager',
    title: 'Permit Manager',
    description: 'Permits, expiry & reminders',
    category: 'safety',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/permit-manager',
    icon: 'document-text-outline',
  },
  {
    id: 'osha-compliance',
    title: 'OSHA / Compliance',
    description: 'Clause checklists & audit score',
    category: 'safety',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/osha-compliance',
    icon: 'shield-checkmark-outline',
  },
  // Category 5 — Documents
  {
    id: 'invoice-generator',
    title: 'Invoice Generator',
    description: 'Line items, tax & PDF',
    category: 'documents',
    phase: 'basic',
    implementation: 'live',
    href: '/(app)/tools/invoice-generator',
    icon: 'receipt-outline',
  },
  {
    id: 'contract-builder',
    title: 'Contract Builder',
    description: 'Templates & clauses to PDF',
    category: 'documents',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/contract-builder',
    icon: 'document-attach-outline',
  },
  {
    id: 'progress-report',
    title: 'Progress Report',
    description: 'Period report with photos',
    category: 'documents',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/progress-report',
    icon: 'newspaper-outline',
  },
  {
    id: 'rfi-tracker',
    title: 'RFI Tracker',
    description: 'Requests for information & responses',
    category: 'documents',
    phase: 'mid',
    implementation: 'live',
    href: '/(app)/tools/rfi-tracker',
    icon: 'chatbubbles-outline',
  },
  {
    id: 'punch-list',
    title: 'Punch List',
    description: 'Snags, photos & verification',
    category: 'documents',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/punch-list',
    icon: 'list-circle-outline',
  },
  {
    id: 'site-inspection-report',
    title: 'AI Site Inspection Report',
    description: 'Photo steps, AI descriptions, location tagging & PDF export',
    category: 'documents',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/site-inspection-report',
    icon: 'camera-outline',
  },
  // Category 6 — Analytics
  {
    id: 'analytics-dashboard',
    title: 'Analytics Dashboard',
    description: 'Portfolio KPIs & SPI/CPI',
    category: 'analytics',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/analytics-dashboard',
    icon: 'pie-chart-outline',
  },
  {
    id: 'bim-viewer',
    title: 'BIM Viewer',
    description: 'Viewer links & ACC / cloud sessions',
    category: 'analytics',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/bim-viewer',
    icon: 'apps-outline',
  },
  {
    id: 'drone-report',
    title: 'Drone / Site Photos',
    description: 'Geo-tagged photo reports',
    category: 'analytics',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/drone-report',
    icon: 'airplane-outline',
  },
  {
    id: 'carbon-footprint',
    title: 'Carbon Footprint',
    description: 'Embodied CO₂ from key inputs',
    category: 'analytics',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/carbon-footprint',
    icon: 'leaf-outline',
  },
  {
    id: 'ai-risk-predictor',
    title: 'AI Risk Predictor',
    description: 'Advisory risk scores (on-device)',
    category: 'analytics',
    phase: 'advanced',
    implementation: 'live',
    href: '/(app)/tools/ai-risk-predictor',
    icon: 'sparkles-outline',
  },

  // Roadmap — coming soon (offline-first where applicable)
  {
    id: 'unit-converter',
    title: 'Engineering Unit Converter',
    description:
      'Length, area, volume, weight, pressure, force, temperature — metric & imperial, all common units.',
    category: 'engineering',
    phase: 'basic',
    implementation: 'placeholder',
    href: '/(app)/tools/unit-converter',
    icon: 'swap-horizontal-outline',
  },
  {
    id: 'bar-bending-schedule',
    title: 'Bar Bending Schedule (BBS)',
    description: 'Cutting lengths, bend deductions, hook allowances, bar shapes — export PDF or table.',
    category: 'engineering',
    phase: 'basic',
    implementation: 'placeholder',
    href: '/(app)/tools/bar-bending-schedule',
    icon: 'git-network-outline',
  },
  {
    id: 'rate-analysis',
    title: 'Rate Analysis Calculator',
    description: 'Cost per unit: PCC, RCC, brickwork, plaster, painting — material, labour & overhead.',
    category: 'estimation',
    phase: 'basic',
    implementation: 'placeholder',
    href: '/(app)/tools/rate-analysis',
    icon: 'cash-outline',
  },
  {
    id: 'stair-calculator',
    title: 'Stair Calculator',
    description: 'Riser, tread, riser count, going, headroom — with code-style checks.',
    category: 'engineering',
    phase: 'basic',
    implementation: 'placeholder',
    href: '/(app)/tools/stair-calculator',
    icon: 'trail-sign-outline',
  },
  {
    id: 'development-length',
    title: 'Development Length Calculator',
    description: 'Anchorage length Ld for rebar per IS 456 / ACI 318 — pull-out at joints.',
    category: 'engineering',
    phase: 'basic',
    implementation: 'placeholder',
    href: '/(app)/tools/development-length',
    icon: 'link-outline',
  },
  {
    id: 'gps-area-measurer',
    title: 'GPS Area Measurer',
    description: 'Walk a site perimeter, plot area from GPS — export map with dimensions.',
    category: 'instruments',
    phase: 'mid',
    implementation: 'placeholder',
    href: '/(app)/tools/gps-area-measurer',
    icon: 'navigate-outline',
  },
  {
    id: 'steel-section-properties',
    title: 'Steel Section Properties',
    description: 'IS / BS / AISC sections — I-beams, channels, angles, hollows — dimensions, I, Z, r.',
    category: 'reference',
    phase: 'basic',
    implementation: 'placeholder',
    href: '/(app)/tools/steel-section-properties',
    icon: 'grid-outline',
  },
  {
    id: 'concrete-grade-reference',
    title: 'Concrete Grade Reference',
    description: 'M10–M60: fck, use case, w/c, min cement — IS 456 / ACI 318 / BS 8110.',
    category: 'reference',
    phase: 'basic',
    implementation: 'placeholder',
    href: '/(app)/tools/concrete-grade-reference',
    icon: 'layers-outline',
  },
  {
    id: 'soil-classification-guide',
    title: 'Soil Classification Guide',
    description: 'USCS + IS: ID, bearing ranges, types — field use without a lab.',
    category: 'reference',
    phase: 'basic',
    implementation: 'placeholder',
    href: '/(app)/tools/soil-classification-guide',
    icon: 'earth-outline',
  },
  {
    id: 'material-density-table',
    title: 'Material Density Table',
    description: '60+ construction materials — unit weights for load and quantity checks.',
    category: 'reference',
    phase: 'basic',
    implementation: 'placeholder',
    href: '/(app)/tools/material-density-table',
    icon: 'scale-outline',
  },
  {
    id: 'load-combination-reference',
    title: 'Load Combination Reference',
    description: 'IS 875 / ASCE 7 combinations — dead, live, wind, seismic.',
    category: 'reference',
    phase: 'basic',
    implementation: 'placeholder',
    href: '/(app)/tools/load-combination-reference',
    icon: 'flash-outline',
  },
  {
    id: 'standard-drawings-library',
    title: 'Standard Drawings Library',
    description: 'Details: column–beam, pile cap, retaining wall, slab edge — offline viewer.',
    category: 'reference',
    phase: 'mid',
    implementation: 'placeholder',
    href: '/(app)/tools/standard-drawings-library',
    icon: 'images-outline',
  },
  {
    id: 'digital-spirit-level',
    title: 'Digital Spirit Level',
    description: 'Accelerometer angles — horizontal / vertical, degrees & mm/m.',
    category: 'instruments',
    phase: 'basic',
    implementation: 'placeholder',
    href: '/(app)/tools/digital-spirit-level',
    icon: 'analytics-outline',
  },
  {
    id: 'noise-level-meter',
    title: 'Noise Level Meter',
    description: 'Site noise in dB — logged with timestamp for compliance records.',
    category: 'instruments',
    phase: 'mid',
    implementation: 'placeholder',
    href: '/(app)/tools/noise-level-meter',
    icon: 'mic-outline',
  },
  {
    id: 'drawing-dimension-scaler',
    title: 'Drawing Dimension Scaler',
    description: 'Photo a drawing, set scale from two points, measure any dimension on the image.',
    category: 'instruments',
    phase: 'mid',
    implementation: 'placeholder',
    href: '/(app)/tools/drawing-dimension-scaler',
    icon: 'scan-outline',
  },
  {
    id: 'site-sun-path',
    title: 'Site Location + Sun Path',
    description: 'Sunrise/sunset and sun angle by hour — formwork timing & shadows.',
    category: 'instruments',
    phase: 'mid',
    implementation: 'placeholder',
    href: '/(app)/tools/site-sun-path',
    icon: 'sunny-outline',
  },
  {
    id: 'multi-span-beam-analyser',
    title: 'Multi-Span Beam Analyser',
    description: '2–5 spans, UDL + point loads — BMD & SFD.',
    category: 'engineering',
    phase: 'mid',
    implementation: 'placeholder',
    href: '/(app)/tools/multi-span-beam-analyser',
    icon: 'git-branch-outline',
  },
  {
    id: 'two-way-slab-designer',
    title: 'Two-Way Slab Designer',
    description: 'IS 456 two-way slabs — moment coefficients, steel both ways, deflection.',
    category: 'engineering',
    phase: 'mid',
    implementation: 'placeholder',
    href: '/(app)/tools/two-way-slab-designer',
    icon: 'square-outline',
  },
  {
    id: 'pile-load-calculator',
    title: 'Pile Load Calculator',
    description: 'Skin friction + end bearing — driven & bored, Meyerhof / IS-style methods.',
    category: 'engineering',
    phase: 'advanced',
    implementation: 'placeholder',
    href: '/(app)/tools/pile-load-calculator',
    icon: 'arrow-down-outline',
  },
  {
    id: 'retaining-wall-stability',
    title: 'Retaining Wall Stability',
    description: 'Gravity / cantilever — overturning, sliding, bearing — IS 3370 / EC7.',
    category: 'engineering',
    phase: 'advanced',
    implementation: 'placeholder',
    href: '/(app)/tools/retaining-wall-stability',
    icon: 'shield-outline',
  },
  {
    id: 'wind-load-calculator',
    title: 'Wind Load Calculator',
    description: 'IS 875 Part 3 / ASCE 7 — Vb, terrain, pressure coefficients.',
    category: 'engineering',
    phase: 'mid',
    implementation: 'placeholder',
    href: '/(app)/tools/wind-load-calculator',
    icon: 'cloud-outline',
  },
  {
    id: 'cable-sizing',
    title: 'Cable Sizing Calculator',
    description: 'Cross-section for current, voltage drop, length — IEC / BS 7671.',
    category: 'mep',
    phase: 'mid',
    implementation: 'placeholder',
    href: '/(app)/tools/cable-sizing',
    icon: 'flash-outline',
  },
  {
    id: 'pipe-sizing-flow',
    title: 'Pipe Sizing & Flow',
    description: 'Diameter for flow & pressure — Hazen-Williams, hot/cold water.',
    category: 'mep',
    phase: 'mid',
    implementation: 'placeholder',
    href: '/(app)/tools/pipe-sizing-flow',
    icon: 'water-outline',
  },
  {
    id: 'ac-load-tonnage',
    title: 'AC Load & Tonnage',
    description: 'Cooling load (BTU/TR) from area, occupancy, windows, climate.',
    category: 'mep',
    phase: 'mid',
    implementation: 'placeholder',
    href: '/(app)/tools/ac-load-tonnage',
    icon: 'snow-outline',
  },
  {
    id: 'electrical-load-schedule',
    title: 'Electrical Load Schedule',
    description: 'Circuits, connected load, demand factor, kVA, generator sizing.',
    category: 'mep',
    phase: 'mid',
    implementation: 'placeholder',
    href: '/(app)/tools/electrical-load-schedule',
    icon: 'battery-charging-outline',
  },
  {
    id: 'construction-glossary',
    title: 'Construction Terms Glossary',
    description: 'Civil & structural terms — English + Arabic + Urdu + Hindi, offline search.',
    category: 'knowledge',
    phase: 'basic',
    implementation: 'placeholder',
    href: '/(app)/tools/construction-glossary',
    icon: 'book-outline',
  },
  {
    id: 'code-quick-reference',
    title: 'IS / BS / ACI Code Quick Reference',
    description: 'Key clauses: IS 456, 875, 1893, BS 8110, ACI 318 — searchable offline.',
    category: 'knowledge',
    phase: 'basic',
    implementation: 'placeholder',
    href: '/(app)/tools/code-quick-reference',
    icon: 'library-outline',
  },
  {
    id: 'site-engineer-daily-checklist',
    title: 'Site Engineer Daily Checklist',
    description: 'Walkthrough, safety, materials, quality, drawings, workforce — daily routine.',
    category: 'knowledge',
    phase: 'basic',
    implementation: 'placeholder',
    href: '/(app)/tools/site-engineer-daily-checklist',
    icon: 'clipboard-outline',
  },
  {
    id: 'construction-defects-guide',
    title: 'Construction Defects Visual Guide',
    description: 'Honeycomb, cracks, delamination, efflorescence — causes & fixes.',
    category: 'knowledge',
    phase: 'mid',
    implementation: 'placeholder',
    href: '/(app)/tools/construction-defects-guide',
    icon: 'camera-outline',
  },
  {
    id: 'material-price-tracker',
    title: 'Local Material Price Tracker',
    description: 'Crowdsourced cement, steel, sand, bricks by city — weekly updates.',
    category: 'procurement',
    phase: 'advanced',
    implementation: 'placeholder',
    href: '/(app)/tools/material-price-tracker',
    icon: 'trending-up-outline',
  },
  {
    id: 'subcontractor-rate-card',
    title: 'Subcontractor Rate Card Builder',
    description: 'Save labour rates by trade for your region — use in estimates.',
    category: 'procurement',
    phase: 'mid',
    implementation: 'placeholder',
    href: '/(app)/tools/subcontractor-rate-card',
    icon: 'people-outline',
  },
  {
    id: 'equipment-hire-rates',
    title: 'Equipment Hire Rate Reference',
    description: 'Typical hire rates: excavators, cranes, pumps, scaffolding — by region.',
    category: 'procurement',
    phase: 'mid',
    implementation: 'placeholder',
    href: '/(app)/tools/equipment-hire-rates',
    icon: 'construct-outline',
  },
];

export const CATEGORY_LABELS: Record<ToolCategoryId | 'all', string> = {
  all: 'All',
  estimation: 'Estimation',
  projects: 'Projects',
  engineering: 'Engineering',
  safety: 'Safety',
  documents: 'Documents',
  analytics: 'Analytics',
  reference: 'Reference',
  instruments: 'Site tools',
  mep: 'MEP',
  knowledge: 'Knowledge',
  procurement: 'Procurement',
};
